version: '2'
services:
  jpymeta:
    image: analysis/meta-notebook
    build: ./meta-notebook 
    hostname: jpymeta 
    container_name: jpymeta
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - /etc/gshadow:/etc/gshadow:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home:/home
      - /data:/data
    ports:
      - 8888:8888
    environment:
      - USER=$USER
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    volumes:
      - /data/mongo:/data/db
  mongo-express:
    image: mongo-express
    hostname: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    links:
      - mongo:mongo
    ports:
      - 8081:8081
  redis:
    image: redis
    hostname: redis
    container_name: redis
